# First Stage
FROM microsoft/aspnetcore-build:2.0.0

RUN mkdir /build
WORKDIR /build

COPY src/Hops/ .
RUN dotnet restore

RUN dotnet publish -c Release -o out

# Second Stage
FROM microsoft/aspnetcore:2.0.0

WORKDIR /app
COPY --from=0 /build/out .

ENV ASPNETCORE_URLS http://+:5000 
EXPOSE 5000/tcp

ENTRYPOINT dotnet Hops.dll