# First Stage
FROM microsoft/dotnet:2.0-sdk

RUN mkdir /build
WORKDIR /build

COPY src/Hops/ .
RUN dotnet restore

RUN dotnet publish -c Release -o out

# Second Stage
FROM microsoft/dotnet:2.0-runtime

WORKDIR /app
COPY --from=0 /build/out .

EXPOSE 5000/tcp
ENTRYPOINT dotnet Hops.dll --server.urls http://0.0.0.0:5000
